Split keys configuration content into separate topics.
ConsenSys/doc.tessera pull request #62
Opened 2021-03-10 21:05 UTC by bgravenorst

Signed-off-by: Byron Gravenorst <byron.gravenorst@consensys.net>

## Pull Request Description
Split keys configuration content into separate topics.

## Fixed Issue(s)
Fixes #52

2021-03-11 07:40 UTC, NicolasMassart requested changes
redirects required

2021-03-11 07:40 UTC, NicolasMassart commented on mkdocs.yml
> -    - Generate keys: HowTo/Generate-keys.md
Requires a redirect from this to something like an overview

2021-03-11 07:40 UTC, NicolasMassart commented on mkdocs.yml
> -      - Keys: HowTo/Configure/Keys.md
Requires a redirect: maybe redirect to the overview page would be the best

2021-03-15 17:36 UTC, Krish1979 approved these changes
LGTM

2021-03-16 03:59 UTC, bgravenorst commented on mkdocs.yml
> -    - Generate keys: HowTo/Generate-keys.md
Done.

2021-03-16 03:59 UTC, bgravenorst commented on mkdocs.yml
> -      - Keys: HowTo/Configure/Keys.md
Done

2021-03-16 04:15 UTC, MadelineMurray approved these changes

2021-03-16 07:14 UTC, NicolasMassart approved these changes
Looks good to me.

2021-03-16 21:18 UTC, merged