add build guide
ConsenSys/doc.tessera pull request #82
Opened 2021-05-04 21:59 UTC by alexandratran

## Pull Request Description

Add build guide

## Fixed Issue(s)

fixes #73

2021-05-05 08:39 UTC, NicolasMassart commented on docs/HowTo/Get-started/Build-From-Source.md
> +./gradlew build -x test
Have you tried with `./gradlew installDist` ?
It may be simpler as you can find binaries directly under `tessera-dist/build/install/tessera-dist` without the need to unpack an archive.

2021-05-06 17:12 UTC, NicolasMassart approved these changes
Looks good to me.

2021-05-12 10:47 UTC, chris-j-h approved these changes

2021-05-12 10:47 UTC, chris-j-h commented on docs/HowTo/Get-started/Build-From-Source.md
> +./gradlew installDist
I would suggest keeping this as `./gradlew build` for the time being.  We are in the process of migrating our release artifacts from .jar to zipped distributions.  Until then, some external tools (such as quorum examples) require `.jar` distributions.

2021-05-12 12:06 UTC, chris-j-h requested changes
accidentally approved

2021-05-13 09:26 UTC, chris-j-h requested changes

2021-05-13 09:26 UTC, chris-j-h commented on docs/HowTo/Get-started/Build-From-Source.md
> +````
Verification steps need updating - I raised a PR against your branch https://github.com/alexandratran/doc.tessera/pull/1

2021-05-14 09:08 UTC, chris-j-h approved these changes
looks good!

2021-05-14 09:28 UTC, merged